[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs", "openssh"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm run start:prod"
